### ISSUE TITLE
Possible bug in the CarvanaClassifier.predict() method

### ISSUE THREAD

**Issue by ceshine** [EKami/carvana-challenge#1]
First of all, thanks for sharing this well written solution!

For an image of size (N, N). The following line of code seems to return an array of size (N,), but the desired effect is to classify every pixel in that image, that is, an array of size(N, N):

https://github.com/EKami/carvana-challenge/blob/517c2e519583a64aec7848d1375ad6078a2f6cab/src/nn/classifier.py#L197

So maybe change it to `pred_arr = pred.data.cpu().numpy()` would make more sense. 

(I use pytorch 0.2.0.post2)

**Comment by godardt** [comment]
Oh man thank you for this. I was chasing this bug for hours... [Here is the commit](https://github.com/EKami/carvana-challenge/commit/ff24a738b195aa310c5d1c4ae09d9479f399e529) which fix the bug. Such a stupid mistake of mine...

**Comment by ceshine** [comment]
Cool. Glad to be of help.
